import * as core from "@actions/core";
import type { GitHub } from "@actions/github/lib/utils";
import type {
  AnalysisResult,
  DriftResult,
  DocPatch,
  PatchPRResult,
  PRContext,
} from "./types";

// ─── Apply Patch to Doc Content ───────────────────────────────────────────────

/**
 * Applies a simple text replacement: replaces `staleText` with `suggestedText`
 * in the original doc content. Returns null if the stale text is not found.
 */
function applyPatch(
  originalContent: string,
  staleText: string,
  suggestedText: string
): string | null {
  if (!originalContent.includes(staleText)) {
    core.debug(`Stale text not found verbatim in doc — skipping patch.`);
    return null;
  }
  // Intentionally replaces only the first occurrence. The LLM's staleText targets
  // a specific passage, so a single surgical replacement is the safest behavior.
  return originalContent.replace(staleText, suggestedText);
}

// ─── Collect Patches ──────────────────────────────────────────────────────────

function collectPatches(
  result: AnalysisResult,
  docContents: Map<string, string>
): DocPatch[] {
  const patches: DocPatch[] = [];
  const seenFiles = new Map<string, string>(); // filePath → current patched content

  const actionable = result.driftResults.filter(
    (r): r is DriftResult & { staleText: string; suggestedText: string } =>
      r.meetsThreshold &&
      r.staleText !== undefined &&
      r.suggestedText !== undefined
  );

  for (const drift of actionable) {
    const filePath = drift.matchedSection.filePath;
    const baseContent =
      seenFiles.get(filePath) ?? docContents.get(filePath) ?? "";

    const patched = applyPatch(
      baseContent,
      drift.staleText,
      drift.suggestedText
    );

    if (!patched) continue;

    seenFiles.set(filePath, patched);

    // Upsert patch entry
    const existing = patches.find((p) => p.filePath === filePath);
    if (existing) {
      existing.patchedContent = patched;
    } else {
      patches.push({
        filePath,
        originalContent: baseContent,
        patchedContent: patched,
      });
    }
  }

  return patches;
}

// ─── GitHub API: Create Patch PR ─────────────────────────────────────────────

type OctokitClient = InstanceType<typeof GitHub>;

export class DocPatcher {
  private octokit: OctokitClient;
  private ctx: PRContext;

  constructor(octokit: OctokitClient, ctx: PRContext) {
    this.octokit = octokit;
    this.ctx = ctx;
  }

  async createPatchPR(
    result: AnalysisResult,
    docContents: Map<string, string>
  ): Promise<PatchPRResult | null> {
    const patches = collectPatches(result, docContents);

    if (patches.length === 0) {
      core.info("Auto-patch: no patchable drift found (no verbatim stale text).");
      return null;
    }

    core.info(
      `Auto-patch: creating patch for ${patches.length} doc file(s).`
    );

    const shortSha = this.ctx.headSha.slice(0, 7);
    const patchBranch = `docs/knowledge-diff-${this.ctx.prNumber}-${shortSha}`;

    try {
      // 1. Get base branch SHA
      const { data: refData } = await this.octokit.rest.git.getRef({
        owner: this.ctx.owner,
        repo: this.ctx.repo,
        ref: `heads/${this.ctx.baseRef}`,
      });
      const baseSha = refData.object.sha;

      // 2. Get current tree
      const { data: commitData } = await this.octokit.rest.git.getCommit({
        owner: this.ctx.owner,
        repo: this.ctx.repo,
        commit_sha: baseSha,
      });
      const baseTreeSha = commitData.tree.sha;

      // 3. Create new blobs for each patched doc
      const treeItems: Array<{
        path: string;
        mode: "100644";
        type: "blob";
        sha: string;
      }> = [];

      for (const patch of patches) {
        const { data: blob } = await this.octokit.rest.git.createBlob({
          owner: this.ctx.owner,
          repo: this.ctx.repo,
          content: Buffer.from(patch.patchedContent, "utf-8").toString("base64"),
          encoding: "base64",
        });
        treeItems.push({
          path: patch.filePath,
          mode: "100644",
          type: "blob",
          sha: blob.sha,
        });
      }

      // 4. Create new tree
      const { data: newTree } = await this.octokit.rest.git.createTree({
        owner: this.ctx.owner,
        repo: this.ctx.repo,
        base_tree: baseTreeSha,
        tree: treeItems,
      });

      // 5. Create commit
      const patchedFiles = patches.map((p) => `- ${p.filePath}`).join("\n");
      const { data: newCommit } = await this.octokit.rest.git.createCommit({
        owner: this.ctx.owner,
        repo: this.ctx.repo,
        message: `docs: apply knowledge-diff patches for PR #${this.ctx.prNumber}\n\nUpdated files:\n${patchedFiles}\n\nAuto-generated by knowledge-diff.`,
        tree: newTree.sha,
        parents: [baseSha],
      });

      // 6. Create (or update) branch
      try {
        await this.octokit.rest.git.createRef({
          owner: this.ctx.owner,
          repo: this.ctx.repo,
          ref: `refs/heads/${patchBranch}`,
          sha: newCommit.sha,
        });
      } catch {
        // Branch may already exist from a previous run — update it
        await this.octokit.rest.git.updateRef({
          owner: this.ctx.owner,
          repo: this.ctx.repo,
          ref: `heads/${patchBranch}`,
          sha: newCommit.sha,
          force: true,
        });
      }

      // 7. Open PR
      const filesList = patches.map((p) => `- \`${p.filePath}\``).join("\n");
      const { data: pr } = await this.octokit.rest.pulls.create({
        owner: this.ctx.owner,
        repo: this.ctx.repo,
        title: `docs: fix rationale drift from PR #${this.ctx.prNumber}`,
        head: patchBranch,
        base: this.ctx.baseRef,
        body: `## 📝 Documentation Patch

This PR was auto-generated by [knowledge-diff](https://github.com/marketplace/actions/knowledge-diff) to fix rationale drift detected in #${this.ctx.prNumber}.

### Files updated
${filesList}

### What changed
See the diff for exact text replacements. Please review before merging — AI-generated patches should always be human-approved.

> *Closes the documentation drift flagged in #${this.ctx.prNumber}*`,
      });

      core.info(`Patch PR created: ${pr.html_url}`);

      return {
        patchBranch,
        patchPRNumber: pr.number,
        patchPRUrl: pr.html_url,
      };
    } catch (err) {
      core.error(`Failed to create patch PR: ${err}`);
      return null;
    }
  }
}
